name: Go
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    name: Build
    env:
      GOPATH: /home/runner/go
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          go install github.com/golang/mock/mockgen
          go install github.com/securego/gosec/cmd/gosec
          make install

      - name: Vet
        run: |
          make vet

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          PATH=$(go env GOPATH)/bin:$PATH
          make test
